name: Container Cache
description: "Create a temporary container for the restore package"
inputs:
  cache-image:
    description: "The image name of the cache. Like: `dotnet:6-focal`"
    required: true
  cache-container:
    description: "The container name of the cache. Like: `build-cache-xxxx`"
    required: true
  cache-container-cmd:
    default: 'sleep 20m'
    description: "The cache container startup commands. Default: `sleep 20m`"
    required: false
  cache-source:
    description: "The path of the local cache. Like: `./nuget`"
    required: true
  cache-target:
    description: "The path to the cache in the container. Like: `/root/.nuget/packages`"
    required: true
  code-source:
    description: "The path of the local srouce code. Like: `./src/WebApplication1`"
    required: true
  code-target:
    default: '/code'
    description: "The path to the source code in the container. Default: `/code`"
    required: false
  restore-cmd:
    description: "Restore package command. Like: `dotnet restore --ignore-failed-sources`"
    required: true

runs:
  using: 'node20'
  main: 'entrypoint.js'
  post: 'entrypoint.js'
