#!/bin/bash
set -eux -o pipefail
: "Argv0: $0"
dir="$(dirname "$0")"
read_action_input() {
	"${dir}/read-action-input" "$1"
}

# ==== load input
CACHE_CONTAINER="$(read_action_input cache-container)"
CACHE_SOURCE="$(read_action_input cache-source)"

# ==== docker rm -f build-cache-xx
: "Delete if the cache-container exists"
if docker ps -a --format '{{.Names}}' | grep -q "^${CACHE_CONTAINER}$"; then
    echo "Container ${CACHE_CONTAINER} exists. Deleting..."
    docker rm -f ${CACHE_CONTAINER}
    echo "Container ${CACHE_CONTAINER} has been deleted."
else
    echo "Container ${CACHE_CONTAINER} does not exist."
fi

# ==== 
: "Check if the directory exists and is not empty"
if [ -d "$CACHE_SOURCE" ] && [ -z "$(ls -A "$CACHE_SOURCE")" ]; then
    echo "Directory $CACHE_SOURCE is empty. Deleting it now..."
    rmdir "$CACHE_SOURCE"
    echo "Directory $CACHE_SOURCE has been deleted."
fi

